[package]
name = "ldtk_w2i"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32.1"
eframe = "0.32.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.15.4"
image = { version = "0.25.7", features = ["serde"] }